version: '3.8'

services:
  python-app:
    build: .
    container_name: python_3_13_app
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"